"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Auto_1 = require("./Auto");
var Camion_1 = require("./Camion");
var Moto_1 = require("./Moto");
var RegistroAutomotor_1 = require("./RegistroAutomotor");
var registro = new RegistroAutomotor_1.RegistroAutomotor();
var auto1 = new Auto_1.Auto("Toyota", "Corolla", 2020);
var moto1 = new Moto_1.Moto("Honda", "CB500", 2019);
var camion1 = new Camion_1.Camion("Mercedes", "Actros", 2021);
var moto2 = new Moto_1.Moto("Yamaha", "R6", 2008);
registro.agregarVehiculo(auto1);
registro.agregarVehiculo(moto1);
registro.agregarVehiculo(camion1);
registro.agregarVehiculo(moto2);
var autoModificado = new Auto_1.Auto("Toyota", "Corolla", 2021);
registro.modificarVehiculo(0, autoModificado);
registro.darDeBajaVehiculo(1);
console.log(registro.getVehiculos());
